name: get-iplayer
version: 'latest'
version-script: git -C parts/get-iplayer/src describe --tags  | sed 's/v//'
summary: CLI for downloading content from BBC iplayer
description: |
    Command Line tool for downloading tv and radio programmes from the last 30 days from the BBC iPlayer.

grade: stable 
confinement: strict

apps:
  get-iplayer:
    command: launcher $SNAP/get_iplayer
    plugs:
      - network
      - removable-media
      - home
      - opengl
  get-iplayer-cgi:
    command: launcher $SNAP/get_iplayer.cgi --getiplayer $SNAP/get_iplayer --ffmpeg $SNAP/usr/bin/ffmpeg --port 1935
    plugs:
      - network
      - network-bind
      - removable-media
      - home

parts:
    remove-symlink:
        after: [get-iplayer]
        plugin: nil
        override-build: |
          rm $SNAPCRAFT_STAGE/usr/share/perl5/XML/SAX/ParserDetails.ini
          ln -s /snap/get-iplayer/current/etc/perl/XML/SAX/ParserDetails.ini $SNAPCRAFT_STAGE/usr/share/perl5/XML/SAX/ParserDetails.ini
          snapcraftctl build
    launcher:
        plugin: dump
        source: snap/scripts
    get-iplayer:
        source: https://github.com/get-iplayer/get_iplayer.git
        override-build: |
          last_committed_tag="$(git describe --tags --abbrev=0)"
          last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
          last_released_tag="$(snap info get-iplayer | awk '$1 == "beta:" { print $2 }')"
          # If the latest tag from the upstream project has not been released to
          # beta, build that tag instead of master.
          if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
            git fetch
            git checkout "${last_committed_tag}"
            cd ../src
            git checkout "${last_committed_tag}"
          fi
          snapcraftctl build
        plugin: dump
        stage-packages:
        - perl-base
        - libwww-perl
        - liblwp-protocol-https-perl
        - libmojolicious-perl
        - libxml-simple-perl
        - libxml-libxml-perl
        - libcgi-pm-perl
        - atomicparsley
        - ffmpeg
        - libdb5.3
        - libpulse0
        - libglu1-mesa
